### ISSUE TITLE
BLeak should sanity check configs

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/BLeak#13]
The example config in the README doesn't work. I've traced back the issue to the `getConfigFromSource` function. 

The function works by dynamically creating a function and evaluating the config inside the function. The config needs to explicitly assign the fields on the `exports` object (as the tests do). 

Just writing `export = {...}` (as the configuration does) does not work since that doesn't modify the `exports` object when the function returns.

**Comment by emeryberger** [comment]
There is an example in this pre-print. Maybe that will help? (Meanwhile, I expect @jvilk will be back on-line soon.)

https://jvilk.com/assets/pdf/bleak.pdf

**Comment by rachitnigam** [comment]
The fix is very straightforward (although tracking it down took a while). If you want, I can open a PR to update the example so that it works.

**Comment by jvilk** [comment]
I'll add logic to sanity check configuration files, and to produce decent error messages when they are malformed.

**Comment by jvilk** [comment]
BLeak now checks that every property is properly formed, and should spit out an error message if something is wrong.
