### ISSUE TITLE
Add paper to https://mitmproxy.org/publications/

### ISSUE THREAD

**Issue by mhils** [plasma-umass/BLeak#23]
Hi,

Greetings from the @mitmproxy team. I just stumbled upon BLeak by accident (someone mentioned it in our user survey), and I'm excited to see what you've done with mitmproxy here. Thank you for actually citing us, which sometimes unfortunately isn't the case. We're always happy to support academic research, so if you have any questions please feel free to drop by in our Slack or GitHub repo. Also, I'd be more than happy to have you on https://mitmproxy.org/publications/ if you want to add yourself - link is on the page. 😃

**Comment by emeryberger** [comment]
Done, thanks! Also, great idea to just have people edit the file on github. I am stealing that one :).

**Comment by jvilk** [comment]
Oh, that was my survey response! Send my regards to the @mitmproxy team for making the only proxy I could find with the features I needed.

How we are actually using mitmproxy is somewhat grotesque; we're starting a websocket server in a plugin to communicate with our node code, which handles rewriting JavaScript to diagnose leaks:

https://github.com/jvilk/mitmproxy-node/blob/master/scripts/proxy.py

Everything works quite well, even across the three operating systems we test against in CI, which is preposterously good.

**Comment by jvilk** [comment]
Also, I'll use the proper BibTeX from the mitmproxy webpage in the camera ready, since we aren't crediting people in our current version. (@emeryberger I just pushed this change.)

**Comment by mhils** [comment]
Thanks. All good - the BiBTeX entry appeared on our website only with the 3.0 release, so you couldn't have known. I'm sorry that you have to interface mitmproxy from node, but I guess that's what you signed up for with this research. :-)
