### ISSUE TITLE
BLeak cannot access websites run on localhost:8080

### ISSUE THREAD

**Issue by mjayprateek** [plasma-umass/BLeak#31]
Environment: Mac OSX High Sierra
Python versions - python : 2.7.0 and python3 : 3.7.0
Mitmproxy : 4.0.1 (This is using python 3.7)
Bleak was installed from npm

Command : bleak run --config bleak_config.js --out bleak

config file (in txt because of github restrictions) is attached (jquery.min.js has been copy-pasted at the top. Actual config starts from line 17) 
[config.txt](https://github.com/plasma-umass/BLeak/files/2280003/config.txt)

BLeaks opens the browser which displays the following (while accessing localhost:8080):
```
502 Bad Gateway
ProtocolException("Invalid server address: ('localhost', 8080)\r\nThe proxy shall not connect to itself.")
```

On terminal it throws the following error:

```
DevTools listening on ws://127.0.0.1:49277/devtools/browser/e20ca5ea-a43f-40d2-9e72-91cb461810a4
2018-08-11 12:43:53.148 Google Chrome[70488:2536413] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
2018-08-11 12:43:53.436 Google Chrome[70488:2536413] Errors logged by ksadmin: KSKeyedPersistentStore store directory does not exist. [com.google.UpdateEngine.CommonErrorDomain:501 - '/Library/Google/GoogleSoftwareUpdate/TicketStore' - 'KSKeyedPersistentStore.m:327']
KSPersistentTicketStore failed to load tickets. (productID: com.google.Chrome) [com.google.UpdateEngine.CoreErrorDomain:1051 - '/Library/Google/GoogleSoftwareUpdate/TicketStore/Keystone.ticketstore'] (KSKeyedPersistentStore store directory does not exist. - '/Library/Google/GoogleSoftwareUpdate/TicketStore' [com.google.UpdateEngine.CommonErrorDomain:501])
ksadmin cannot access the ticket store:<KSUpdateError:0x7fc27f60ffa0
	domain="com.google.UpdateEngine.CoreErrorDomain"
	code=1051
	userInfo={
		function = "-[KSProductKeyedStore(ProtectedMethods) errorForStoreError:productID:message:timeoutMessage:]";
		date = 2018-08-11 07:13:53 +0000;
		productids = {(
			"com.google.Chrome"
		)};
		filename = "KSProductKeyedStore.m";
		line = 102;
		NSFilePath = "/Library/Google/GoogleSoftwareUpdate/TicketStore/Keystone.ticketstore";
		NSUnderlyingError = <KSError:0x7fc2813068d0
			domain="com.google.UpdateEngine.CommonErrorDomain"
			code=501
			userInfo={
				NSLocalizedDescription = "KSKeyedPersistentStore store directory does not exist.";
				line = 327;
				filename = "KSKeyedPersistentStore.m";
				function = "-[KSKeyedPersistentStore(PrivateMethods) validateStorePath]";
				NSFilePath = "/Library/Google/GoogleSoftwareUpdate/TicketStore";
				date = 2018-08-11 07:13:53 +0000;
			}
		>;
		NSLocalizedDescription = "KSPersistentTicketStore failed to load tickets.";
	}
>
Error: socket disconnect
[=                   ] 6% [3/48] 0.1s (ETA 1.0s) Waiting for loop[0].check() === true
```

**Comment by jvilk** [comment]
Are you trying to navigate to the url `http://localhost:8080/`? BLeak runs a proxy server on port 8080, so if you navigate to `http://localhost:8080/`, then you will be asking the proxy to connect to itself. If this is the case, you will need to configure your web application to use a different port.

**Comment by jvilk** [comment]
If this is hard to do, I could add an option that lets you configure the proxy port.

**Comment by mjayprateek** [comment]
Thanks John! 

Though, I could only execute BLeak after removing jquery.min.js from the beginning of the config.js. I had copy-pasted jquery.min.js at the beginning to make use of jquery selectors. Not sure why it messed up with the proxy.

The script does run after that fix, but it stops midway and throws this error on the terminal:

```
http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.js:2100:18 Uncaught TypeError: Cannot read property 'focus' of undefined
    at HTMLButtonElement.<anonymous> (http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.js:2101:19)
    at invoke (http://localhost:4502/bleak_agent_transform.js:26:15)
    at bound (http://localhost:4502/bleak_agent_transform.js:32:75)
undefined
  http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.js:2100:18
  invoke at http://localhost:4502/bleak_agent_transform.js:25:14
  bound at http://localhost:4502/bleak_agent_transform.js:31:74

http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.js:2100:18 Uncaught TypeError: Cannot read property 'focus' of undefined
    at HTMLInputElement.<anonymous> (http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.js:2101:19)
    at invoke (http://localhost:4502/bleak_agent_transform.js:26:15)
    at bound (http://localhost:4502/bleak_agent_transform.js:32:75)
undefined
  http://localhost:4502/etc.clientlibs/granite/ui/components/coral/foundation/clientlibs/foundation.js:2100:18
  invoke at http://localhost:4502/bleak_agent_transform.js:25:14
  bound at http://localhost:4502/bleak_agent_transform.js:31:74

undefined:0:0 Uncaught ReferenceError: BLeakConfig is not defined
    at <anonymous>:1:1
undefined
  

[==                  ] 10% [19/187] 21.0s (ETA 185.8s) Advancing to next state loop[2].next()Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by jvilk** [comment]
Hmm, that is odd. The error message indicated that something was trying to access `localhost:8080`. Good to know that the fix was relatively trivial.

Regarding jQuery, the input script is evaluated in the browser *and in Node.js*. We have to evaluate it in both environments to retrieve configuration information. You can put a condition around jQuery; perhaps that would fix the issue?:

```javascript
if (typeof(process) === 'undefined') {
  // Browser; go ahead and install jQuery
}
```

It sounds like the second issue occurs during leak diagnosis, which is BLeak's second phase. If it produced a `bleak_results.json` file in the output directory, then it completed leak detection and failed on leak diagnosis; `bleak_results.json` should contain leaking paths, but no stack traces. If the issue does occur during leak diagnosis, then the bug is likely in the JavaScript rewriting that BLeak performs.

I can look into this further if the application is open source, and if you provide me with the config file you used. If I can reproduce the issue locally, it may be a quick fix.

**Comment by jvilk** [comment]
(If the application is not open source, but you are OK with providing me with access to it, then I am still happy to look.)

**Comment by jvilk** [comment]
If you can't share anything, then you should examine the rewritten code next to the original code to see if anything looks funky. Oftentimes something appears obviously wrong in the rewritten code. You can manually run BLeak's code rewriting process from the command line to examine the rewritten code:

```
bleak transform-javascript --in path/to/file.js --out output_directory
```

**Comment by mjayprateek** [comment]
I think I can't event share a demo instance as only sales people have access to it. But, I can definitely share config.js here (changed the extension to .txt). 
[config.txt](https://github.com/plasma-umass/BLeak/files/2281902/config.txt).

I can't find bleak_results.json file. So, it looks like the error occurs during leak detection phase. But, I'll give transform command a try and will post the results.

**Comment by mjayprateek** [comment]
@jvilk As explained by you in #32 here also I'm making the same mistake. The config file describes the flow which reloads the html in the browser, which does not work for BLeak which is more relevant for SPAs.

I think this can be closed.
