### ISSUE TITLE
Installing bleak-detector fails at mitmproxy@2.1.0 postinstall: `scripts/install_python_deps.py`

### ISSUE THREAD

**Issue by gvbrakel** [plasma-umass/BLeak#35]
I run into the following issue when installing bleak-detector:

----------------------------------------------------------------------------------------------
$ npm install -g bleak-detector
C:\Users\username\AppData\Roaming\npm\bleak ->
C:\Users\username\AppData\Roaming\npm\node_modules\bleak-detector\dist\node\cli\bleak.js

> bufferutil@3.0.5 install C:\Users\username\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil
> prebuild-install || node-gyp rebuild

> utf-8-validate@4.0.2 install C:\Users\username\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\utf-8-validate
> prebuild-install || node-gyp rebuild

> mitmproxy@2.1.0 postinstall C:\Users\username\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\mitmproxy
> scripts/install_python_deps.py

'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mitmproxy@2.1.0 postinstall: `scripts/install_python_deps.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mitmproxy@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-10-26T06_07_20_186Z-debug.log

----------------------------------------------------------------------------------------------  

$ mitmdump --version
Mitmproxy: 4.0.4 binary
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.16299

$ python -V
Python 3.7.1

I see the same problems when running npm install -g mitmproxy. Also for earlier version 2.0.4

As an alternative, I also tried to use yarn, but that resulted in the same issue.

Do you have any suggestion how to proceed with this?

**Comment by ysc1** [comment]
Hello gvbrakel,

Just wanted to check if you are able to resolve the error as we are facing the same error.
We are also having all the valid versions Mitproxy and Python but still getting the same error log which you have mentioned in your query.

It would be great if you can let us know workaround or solution for the problem.

**Comment by gvbrakel** [comment]
Hi,

Sorry, did not receive any response at all. So, we looked at an other tool


Op ma 7 jan. 2019 15:49 schreef ysc1 <notifications@github.com:

**Comment by ysc1** [comment]
Hi,
Will you be able to tell us the alternate tool name? which you have used to find Memory Leakages in Java script application ?

**Comment by gvbrakel** [comment]
We started with Alibaba JS-memory analysor:
https://github.com/alibaba/JS-Memory-Analysor
https://github.com/alibaba/JS-Memory-Analysor.git
That provides a graph of the biggest memory leaks. But it is based on the
chrome dev tools.

Tips can also be found at
https://medium.com/outsystems-experts/beyond-memory-leaks-in-javascript-d27fd48ae67e
In our case the most problems were related to timers that were not
cancelled.
You can also install the following extension in chrome that adds a Timer
tab to the dev tools: setInterval sniffer 1.0
That turned out to be very helpfull. You get an overview of the active and
cancelled timers.

Hope this helps.


Op di 8 jan. 2019 om 04:31 schreef ysc1 <notifications@github.com>:

**Comment by ysc1** [comment]
Thanks a lot gvbrakel, We will try alibaba memory analysor.

**Comment by buddyp450** [comment]
I had the same issue as the original post but happened to notice the package itself uses yarn natively to build so I just used yarn to install it globally and it worked.

**Comment by jvilk** [comment]
I do recommend using yarn to install BLeak. Sorry for the trouble, everyone. It looks like npm doesn't want to run Python scripts.

**Comment by jvilk** [comment]
I just released v1.2.2, which should fix this problem.
