### ISSUE TITLE
Just sits there

### ISSUE THREAD

**Issue by DangerStu** [plasma-umass/BLeak#41]
Hi,

I have installed python 3.7 and mitmproxy.

I have set up a config file to test my site when I run bleak it generates the output folder and copies in the config file and then nothing else happens.

I then configured a second config to open a 3rd party site and the same thing happens.

any tips on debugging what is happening would be appreciated

exports.url = "http://www.ocgov.com";
// Runs your program in a loop. Each item in the array is a `state`. Each `state` has a "check"
// function, and a "next" function to transition to the next state in the loop. These run
// in the global scope of your web app.
// BLeak assumes that the app is in the first state when it navigates to the URL. If you specify
// optional setup states, then it assumes that the final setup state transitions the web app to
// the first state in the loop.
// The last state in the loop must transition back to the first.
exports.loop = [
  // First state
  {
    // Return 'true' if the web application is ready for `next` to be run.
    check: function() {
      // Example: `group-listing` must be on the webpage
      return !!document.getElementById('imgPopMenu3');
    },
    // Transitions to the next state.
    next: function() {
      // Example: Navigate to the first thread
      document.getElementById("imgPopMenu3").click();
    }
  },
  // Second (and last) state
  {
    check: function() {
      // Example: Make sure the body of the thread has loaded.
      return !!document.getElementById('imgPopMenu2');
    },
    // Since this is the last state in the loop, it must transition back to the first state.
    next: function() {
      // Example: Click back to group listing
      document.getElementById('imgPopMenu2').click();
    }
  }
];

yarn run bleak run --config C:\Users\dange\bleak\ocgov.config.js --out C:\Users\dange\bleak\bleak_ocgog

**Comment by DangerStu** [comment]
found websocket issue caused by mitmproxy setup,

**Comment by emeryberger** [comment]
@DangerStu, can you elaborate? Just in case someone else runs into a similar problem. Thanks.

**Comment by DangerStu** [comment]
I'm on windows 10, the post deploy script errors out because it's pathed 'scripts/install_python_deps.py' and npm has an issue with that for me, 
To rectify, I added --force to the install and then  copied in the requirements.txt file into the scripts folder and ran install_python_deps.py manually.
Initially i had done some googling and people suggested using yarn to do the install, which worked but put the packages in a different place 
Also install mitmproxy before installing bleak

**Comment by jvilk** [comment]
I fixed this issue in v1.2.2, which uses a version of mitmproxy-node that now runs `node scripts/install_python_deps.js` which then runs python3 or python.

**Comment by DangerStu** [comment]
Hi,
the issue I'm seeing is that on both windows 7 and  windows 10 machines is the install fails with 'unknown command script' when the install runs the scripts/install_python_deps.js.

**Comment by jvilk** [comment]
@DangerStu With 1.2.2? It should install a new version of mitmproxy-node [which now runs `node scripts/install_python_deps.js`](https://github.com/jvilk/mitmproxy-node/blob/master/package.json#L10) instead of `scripts/install_python_deps.py`.

If 1.2.2 is giving you these issues, can I see your `npm-debug.log`? (Run your npm command with `--loglevel verbose` and it should create a log.)
