### ISSUE TITLE
mitmproxy 4.0.1 not available

### ISSUE THREAD

**Issue by dboydor** [plasma-umass/BLeak#43]
What is the right version?  Got this version from the homepage at http://plasma-umass.org/BLeak/

pip install mitmproxy==4.0.1
Collecting mitmproxy==4.0.1
  Could not find a version that satisfies the requirement mitmproxy==4.0.1 (from versions: 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.10, 0.10.1, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13, 0.14.0, 0.15, 0.16, 0.17, 0.18.1, 0.18.2, 0.18.3)
No matching distribution found for mitmproxy==4.0.1

**Comment by jvilk** [comment]
v4.0.0 and higher is the correct version. I don't know why pip isn't finding it; it's at 4.0.4 right now:

https://pypi.org/project/mitmproxy/
